# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenCrossprod <- function(A, B) {
    .Call(`_FasterMatrixMath_eigenCrossprod`, A, B)
}

eigenTCrossprod <- function(A, B) {
    .Call(`_FasterMatrixMath_eigenTCrossprod`, A, B)
}

eigenMapMatMult <- function(A, B) {
    .Call(`_FasterMatrixMath_eigenMapMatMult`, A, B)
}

